<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_TW" sourcelanguage="en">
<context>
    <name>rs21_pc.preset</name>
    <message>
        <source>GT</source>
        <translation>GT賽車模式</translation>
    </message>
    <message>
        <source>Performance</source>
        <translation>性能車模式</translation>
    </message>
    <message>
        <source>Formula 1</source>
        <translation>方程式模式</translation>
    </message>
    <message>
        <source>Karting</source>
        <translation>卡丁車模式</translation>
    </message>
    <message>
        <source>Drift</source>
        <translation>漂移模式</translation>
    </message>
    <message>
        <source>Rally</source>
        <translation>拉力模式</translation>
    </message>
    <message>
        <source>Offical</source>
        <translation>官方</translation>
    </message>
    <message>
        <source>AC-Offical</source>
        <translation>AC-官方</translation>
    </message>
    <message>
        <source>ACC-Offical</source>
        <translation>ACC-官方</translation>
    </message>
    <message>
        <source>AMS2-Offical</source>
        <translation>AMS2-官方</translation>
    </message>
    <message>
        <source>iRacing-Offical</source>
        <translation>iRacing-官方</translation>
    </message>
    <message>
        <source>RF2-Offical</source>
        <translation>RF2-官方</translation>
    </message>
    <message>
        <source>KartKraft-Offical</source>
        <translation>KartKraft-官方</translation>
    </message>
    <message>
        <source>F1-Offical</source>
        <translation>F1-官方</translation>
    </message>
    <message>
        <source>DR2-Offical</source>
        <translation>DR2-官方</translation>
    </message>
    <message>
        <source>AC-POE</source>
        <translation>AC-破鵝</translation>
    </message>
    <message>
        <source>ACC-POE</source>
        <translation>ACC-破鵝</translation>
    </message>
    <message>
        <source>DR2-POE</source>
        <translation>DR2-破鵝</translation>
    </message>
    <message>
        <source>AC-HWRacing</source>
        <translation>AC-鄭晚成</translation>
    </message>
    <message>
        <source>R3E-HWRacing</source>
        <translation>R3E-鄭晚成</translation>
    </message>
</context>
</TS>
